//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FortunaUnofficalAPI.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebRegexPatterns {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebRegexPatterns() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FortunaUnofficalAPI.Data.WebRegexPatterns", typeof(WebRegexPatterns).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=[&quot;&apos;](.+?)[&quot;&apos;].+?title= ?&quot;(.+?)&amp;lt.+?href=&apos;(.+?)&apos;.+?;(.+?)&amp;lt.
        /// </summary>
        internal static string EntryAltArtPattern {
            get {
                return ResourceManager.GetString("EntryAltArtPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;([\s\S]+?)&lt;\/p&gt;.
        /// </summary>
        internal static string EntryBeliefPattern {
            get {
                return ResourceManager.GetString("EntryBeliefPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;\/b&gt; ?&lt;a href=&quot;((?!\/cosmosdex\/planets\/)[\s\S]+?)&quot;.
        /// </summary>
        internal static string EntryCreatorLinkPattern {
            get {
                return ResourceManager.GetString("EntryCreatorLinkPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator: ?&lt;\/b&gt; ?(.+?)&lt;.
        /// </summary>
        internal static string EntryCreatorNameFallbackPattern {
            get {
                return ResourceManager.GetString("EntryCreatorNameFallbackPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;\/b&gt;&lt;a href=&quot;[\s\S]+?&quot;&gt;([\s\S]+?)&lt;.
        /// </summary>
        internal static string EntryCreatorNamePattern {
            get {
                return ResourceManager.GetString("EntryCreatorNamePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;entryquickinfoect&quot;&gt;[\s\S]+?&lt;h5&gt;Patrons and Gods&lt;\/h5&gt;.
        /// </summary>
        internal static string EntryGenericInfoSectionPattern {
            get {
                return ResourceManager.GetString("EntryGenericInfoSectionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h5&gt;Patrons and Gods&lt;\/h5&gt;[\s\S]+?&lt;\/div&gt;.
        /// </summary>
        internal static string EntryGodsPatronSectionPattern {
            get {
                return ResourceManager.GetString("EntryGodsPatronSectionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;entryquickinfoimgtext&quot;&gt;[\s\S]+?&lt;p&gt;.+?&lt;a href=&quot;(.+?)&quot;.+?&quot;&gt;(.+?)&lt;\/a&gt;.
        /// </summary>
        internal static string EntryMainArtCreatorPattern {
            get {
                return ResourceManager.GetString("EntryMainArtCreatorPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img .+? src=&quot;(.+?)&quot;&gt;.
        /// </summary>
        internal static string EntryMainArtPattern {
            get {
                return ResourceManager.GetString("EntryMainArtPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;commonentryheader&quot;&gt;[\s\s]+?.*&lt;u&gt;([\s\S]+?)&lt;[\s\S]+?&lt;h4&gt;([\s\S]+?)&lt;\/h4&gt;.
        /// </summary>
        internal static string EntryNameSectionPattern {
            get {
                return ResourceManager.GetString("EntryNameSectionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;\/b&gt;([\s\S]+?)&lt;br&gt;.
        /// </summary>
        internal static string EntryPatronGodCreatorPattern {
            get {
                return ResourceManager.GetString("EntryPatronGodCreatorPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;entryquickinfoimgtext&quot;&gt;[\s\S]+?&lt;i&gt;(.+?)&lt;.
        /// </summary>
        internal static string EntryQuotePattern {
            get {
                return ResourceManager.GetString("EntryQuotePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;li&gt;&lt;b&gt;(.+?([0-9]+?))&lt;\/b&gt;&lt;\/li&gt;.
        /// </summary>
        internal static string EntryStatsPattern {
            get {
                return ResourceManager.GetString("EntryStatsPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div id=&quot;entryquickinfostats&quot;&gt;[\s\S]+?&lt;\/div&gt;.
        /// </summary>
        internal static string EntryStatsSectionPattern {
            get {
                return ResourceManager.GetString("EntryStatsSectionPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (\&lt;a href=&quot;([a-zA-Z0-9\\-]*)&quot;\&gt;).
        /// </summary>
        internal static string SpeciesNameUrlPattern {
            get {
                return ResourceManager.GetString("SpeciesNameUrlPattern", resourceCulture);
            }
        }
    }
}
